package GUI;

import BUS.KhachHangBUS;
import BUS.PhieuGiamGiaBUS;
import BUS._MessageDialogHelper;
import BUS._SaveData;
import DTO.KhachHangDTO;
import DTO.MatHangDTO;
import DTO.PhieuGiamGiaDTO;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;

public class ChiTietHoaDonDialogGUI extends javax.swing.JDialog {
    private DefaultTableModel model_table;
    private DefaultComboBoxModel model_cbKhachHang;
    private final ArrayList<KhachHangDTO> listKhachHang = new KhachHangBUS().getData();

    /**
     * Creates new form ChiTietHoaDonDialogGUI
     */
    public ChiTietHoaDonDialogGUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        initGioHangTable();
        initThongtin();
        initKhachHang();
    }

    public void initGioHangTable() {
        String[] columnNames = new String[]{"Mã SP", "Tên SP", "Số lượng", "Thành tiền (VNĐ)"};
        model_table = new DefaultTableModel();
        model_table.setColumnIdentifiers(columnNames);

        try {
            tbChiTietGioHang.setModel(model_table);
            tbChiTietGioHang.setFont(new Font("Segoe UI", 0, 12));
            tbChiTietGioHang.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
            for(MatHangDTO item : _SaveData.ChiTietHoaDon) {
                model_table.addRow(new Object[] {
                        item.getMaMH(),
                        item.getTenMH(),
                        item.soLuong_hientai,
                        item.thanhTien_hientai,
                });
            }
            tbChiTietGioHang.setModel(model_table);
        } catch (Exception ex) {
            ex.printStackTrace();
            _MessageDialogHelper.showErrorDialog(this, ex.getMessage(), "Error !");
        }
    }

    public void initThongtin() {
        txtMaHoaDon.setText(_SaveData.maHD);
        txtTenNhanVien.setText(_SaveData.tenNV);
        txtTongHoaDon.setText(String.format("%f %s", _SaveData.tongTien, "VNĐ"));
        txtNgayBan.setText(_SaveData.ngayBan);
    }

    public void initKhachHang() {
        model_cbKhachHang = new DefaultComboBoxModel();
        model_cbKhachHang.addElement("---");
        ArrayList<KhachHangDTO> listKhachHang = new KhachHangBUS().getData();
        for(KhachHangDTO item : listKhachHang) {
           if(!item.getMaKH().equals("---")) {
               model_cbKhachHang.addElement(String.format("%s-%s", item.getMaKH(), item.getTenKH()));
           }
        }
        cbTenKhachHang.setModel(model_cbKhachHang);
        cbTenKhachHang.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                cbTenKhachHangActionListener(e);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        pnThongTinHDChiTiet = new javax.swing.JPanel();
        lbMaHoaDon = new javax.swing.JLabel();
        lbNgayBan = new javax.swing.JLabel();
        lbTongHoaDon = new javax.swing.JLabel();
        lbTenNhanVien = new javax.swing.JLabel();
        lbTenKhachhang = new javax.swing.JLabel();
        txtMaHoaDon = new javax.swing.JTextField();
        txtNgayBan = new javax.swing.JTextField();
        txtTongHoaDon = new javax.swing.JTextField();
        txtTenNhanVien = new javax.swing.JTextField();
        cbTenKhachHang = new javax.swing.JComboBox<>();
        spChiTietGioHang = new javax.swing.JScrollPane();
        tbChiTietGioHang = new javax.swing.JTable();
        btnXacNhan = new javax.swing.JButton();
        txtThoat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Chi tiết hoá đơn");
        setResizable(false);

        pnThongTinHDChiTiet.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin hoá đơn chi tiết", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 13))); // NOI18N

        lbMaHoaDon.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lbMaHoaDon.setText("Mã hoá đơn");

        lbNgayBan.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lbNgayBan.setText("Ngày bán: ");

        lbTongHoaDon.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lbTongHoaDon.setText("Tổng hoá đơn:");

        lbTenNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lbTenNhanVien.setText("Tên nhân viên:");

        lbTenKhachhang.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lbTenKhachhang.setText("Tên khách hàng:");

        txtMaHoaDon.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtMaHoaDon.setEnabled(false);

        txtNgayBan.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtNgayBan.setEnabled(false);

        txtTongHoaDon.setEditable(false);
        txtTongHoaDon.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        txtTenNhanVien.setEditable(false);
        txtTenNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        cbTenKhachHang.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        javax.swing.GroupLayout pnThongTinHDChiTietLayout = new javax.swing.GroupLayout(pnThongTinHDChiTiet);
        pnThongTinHDChiTiet.setLayout(pnThongTinHDChiTietLayout);
        pnThongTinHDChiTietLayout.setHorizontalGroup(
                pnThongTinHDChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnThongTinHDChiTietLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(pnThongTinHDChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lbMaHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lbTongHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lbNgayBan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnThongTinHDChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtMaHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                        .addComponent(txtNgayBan)
                                        .addComponent(txtTongHoaDon))
                                .addGap(18, 18, 18)
                                .addGroup(pnThongTinHDChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbTenKhachhang, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lbTenNhanVien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnThongTinHDChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(cbTenKhachHang, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtTenNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnThongTinHDChiTietLayout.setVerticalGroup(
                pnThongTinHDChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnThongTinHDChiTietLayout.createSequentialGroup()
                                .addGroup(pnThongTinHDChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lbMaHoaDon)
                                        .addComponent(lbTenNhanVien)
                                        .addComponent(txtTenNhanVien)
                                        .addComponent(txtMaHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(pnThongTinHDChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lbNgayBan)
                                        .addComponent(txtNgayBan, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lbTenKhachhang)
                                        .addComponent(cbTenKhachHang))
                                .addGap(21, 21, 21)
                                .addGroup(pnThongTinHDChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lbTongHoaDon)
                                        .addComponent(txtTongHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
        );

        spChiTietGioHang.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chi tiết giỏ hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 13))); // NOI18N
        spChiTietGioHang.setViewportView(tbChiTietGioHang);

        btnXacNhan.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btnXacNhan.setText("Xác nhận");
        btnXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanActionPerformed(evt);
            }
        });

        txtThoat.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        txtThoat.setText("Thoát");
        txtThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtThoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(spChiTietGioHang)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(txtThoat)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnXacNhan)
                                                .addGap(9, 9, 9))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(pnThongTinHDChiTiet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(pnThongTinHDChiTiet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spChiTietGioHang, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtThoat, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                                        .addComponent(btnXacNhan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>

    private void txtThoatActionPerformed(java.awt.event.ActionEvent evt) {
        this.dispose();
    }

    private void btnXacNhanActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private KhachHangDTO cbTenKhachHangActionListener(ActionEvent e) {
        String rawItem = (String) cbTenKhachHang.getSelectedItem();
        if(rawItem.equals("---")) { // trường hợp là khách vãng lại
            KhachHangDTO khachHangDTO = new KhachHangBUS().getItemById("---");
            return khachHangDTO;
        } else { // trường hợp là khách hàng real
            String[] Arr = rawItem.split("-");
            KhachHangDTO khachHangDTO = new KhachHangBUS().getItemById(Arr[0]);
            return khachHangDTO;
        }
    }

    // Variables declaration - do not modify
    private javax.swing.JButton btnXacNhan;
    private javax.swing.JComboBox<String> cbTenKhachHang;
    private javax.swing.JLabel lbMaHoaDon;
    private javax.swing.JLabel lbNgayBan;
    private javax.swing.JLabel lbTenKhachhang;
    private javax.swing.JLabel lbTenNhanVien;
    private javax.swing.JLabel lbTongHoaDon;
    private javax.swing.JPanel pnThongTinHDChiTiet;
    private javax.swing.JScrollPane spChiTietGioHang;
    private javax.swing.JTable tbChiTietGioHang;
    private javax.swing.JTextField txtMaHoaDon;
    private javax.swing.JTextField txtNgayBan;
    private javax.swing.JTextField txtTenNhanVien;
    private javax.swing.JButton txtThoat;
    private javax.swing.JTextField txtTongHoaDon;
    // End of variables declaration
}
