package GUI;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

import BUS.*;
import DTO.MatHangDTO;
import DTO.NhaCungCapDTO;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;

/**
 *
 * @author edgar
 */
public class PanelNhapHangGUI extends javax.swing.JPanel {
    private static MainFormGUI parentForm;
    private DefaultTableModel modelTable_MH;
    private DefaultTableModel modelTable_CTPN;
    private DefaultComboBoxModel modelComboBox_NCC;
    /**
     * Creates new form PanelPhieuNhapGUI
     */
    public PanelNhapHangGUI() {
        initComponents();
        initTableMatHang();
        initNhaCungCap();
        initListCTPN();
    }
    private void initNhaCungCap() {
        modelComboBox_NCC = new DefaultComboBoxModel();
        modelComboBox_NCC.addElement("---");
        for (NhaCungCapDTO item : new NhaCungCapBUS().getData()) {
            modelComboBox_NCC.addElement(item.getTenNCC());
        }
        cbNhaCungCap.setModel(modelComboBox_NCC);
    }
    private void initTableMatHang() {
        String[] columnNames = new String[]{"Mã MH", "Mã LMH", "Tên MH", "Thành tiền", "Số lượng", "Trạng thái"};
        modelTable_MH = new DefaultTableModel();
        modelTable_MH.setColumnIdentifiers(columnNames);

        try {
            tbDanhSachMatHang.setFont(new Font("Segoe UI", 0, 12));
            tbDanhSachMatHang.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
            tbDanhSachMatHang.setModel(modelTable_MH);
            loadMatHang(new MatHangBUS().getData()); // gọi lại hàm load table nhân viên để load lại table
            tbDanhSachMatHang.setDefaultEditor(Object.class, null);
            tbDanhSachMatHang.addMouseListener(new MouseListener() {
                @Override
                public void mouseClicked(MouseEvent e) {

                }

                @Override
                public void mousePressed(MouseEvent e) {
                    tbDanhSachMatHangMouseListener(e);
                }

                @Override
                public void mouseReleased(MouseEvent e) {

                }

                @Override
                public void mouseEntered(MouseEvent e) {

                }

                @Override
                public void mouseExited(MouseEvent e) {

                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
            _MessageDialogHelper.showErrorDialog(this, ex.getMessage(), "Error !");
        }
    }

    public void initListCTPN() {
        String[] columnNames = new String[]{"Mã MH", "Tên MH", "Số lượng",};
        modelTable_CTPN = new DefaultTableModel();
        modelTable_CTPN.setColumnIdentifiers(columnNames);

        tbDanhSachMatHangNhap.setFont(new Font("Segoe UI", 0, 12));
        tbDanhSachMatHangNhap.setModel(modelTable_CTPN);
        tbDanhSachMatHangNhap.setDefaultEditor(Object.class, null);
        tbDanhSachMatHangNhap.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent e) {

            }

            @Override
            public void mousePressed(MouseEvent e) {
                tbDanhSachMatHangNhapMouseListener(e);
            }

            @Override
            public void mouseReleased(MouseEvent e) {

            }

            @Override
            public void mouseEntered(MouseEvent e) {

            }

            @Override
            public void mouseExited(MouseEvent e) {

            }
        });
    }




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        pnThongTinPhieuNhap = new javax.swing.JPanel();
        lbMaPhieuNhap = new javax.swing.JLabel();
        lbMaMatHang = new javax.swing.JLabel();
        lbSoLuongNhap = new javax.swing.JLabel();
        lbNgayNhap = new javax.swing.JLabel();
        lbNhaCungCap = new javax.swing.JLabel();
        txtMaPhieuNhap = new javax.swing.JTextField();
        txtMaMatHang = new javax.swing.JTextField();
        txtSoLuongNhap = new javax.swing.JTextField();
        txtNgayNhap = new javax.swing.JTextField();
        cbNhaCungCap = new javax.swing.JComboBox<>();
        btnLamMoi = new javax.swing.JButton();
        btnTimKiemNV = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnTangSL = new javax.swing.JButton();
        btnGiamSL = new javax.swing.JButton();
        btnHuyDonNhap = new javax.swing.JButton();
        btnXacNhanNhap = new javax.swing.JButton();
        spDanhSachMatHang = new javax.swing.JScrollPane();
        tbDanhSachMatHang = new javax.swing.JTable();
        spDanhSachMatHangNhap = new javax.swing.JScrollPane();
        tbDanhSachMatHangNhap = new javax.swing.JTable();

        pnThongTinPhieuNhap.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin phiếu nhập", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 13))); // NOI18N

        lbMaPhieuNhap.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lbMaPhieuNhap.setText("Mã phiếu nhập:");

        lbMaMatHang.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lbMaMatHang.setText("Mã mặt hàng:");

        lbSoLuongNhap.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lbSoLuongNhap.setText("Số lượng nhập:");

        lbNgayNhap.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lbNgayNhap.setText("Ngày nhập:");

        lbNhaCungCap.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lbNhaCungCap.setText("Nhà cung cấp:");

        txtMaPhieuNhap.setEditable(false);
        txtMaPhieuNhap.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        txtMaMatHang.setEditable(false);
        txtMaMatHang.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        txtSoLuongNhap.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        txtNgayNhap.setEditable(false);
        txtNgayNhap.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        cbNhaCungCap.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        btnLamMoi.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btnLamMoi.setText("Làm mới");
        btnLamMoi.setToolTipText("Làm mới lại form");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        btnTimKiemNV.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btnTimKiemNV.setText("Tìm kiếm");
        btnTimKiemNV.setToolTipText("Tìm kiếm hoá đơn thông qua mã hoá đơn.");
        btnTimKiemNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemNVActionPerformed(evt);
            }
        });

        btnThem.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btnThem.setText("Thêm mặt hàng");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btnXoa.setText("Xoá mặt hàng");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnTangSL.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btnTangSL.setText("Tăng SL nhập");
        btnTangSL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTangSLActionPerformed(evt);
            }
        });

        btnGiamSL.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btnGiamSL.setText("Giảm SL nhập");
        btnGiamSL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGiamSLActionPerformed(evt);
            }
        });

        btnHuyDonNhap.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btnHuyDonNhap.setText("Huỷ đơn nhập");
        btnHuyDonNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyDonNhapActionPerformed(evt);
            }
        });

        btnXacNhanNhap.setText("Xác nhận nhập");
        btnXacNhanNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanNhapActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnThongTinPhieuNhapLayout = new javax.swing.GroupLayout(pnThongTinPhieuNhap);
        pnThongTinPhieuNhap.setLayout(pnThongTinPhieuNhapLayout);
        pnThongTinPhieuNhapLayout.setHorizontalGroup(
                pnThongTinPhieuNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnThongTinPhieuNhapLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(pnThongTinPhieuNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(pnThongTinPhieuNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(lbNgayNhap, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lbSoLuongNhap, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                                                .addComponent(lbMaMatHang, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lbNhaCungCap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lbMaPhieuNhap, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnThongTinPhieuNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnThongTinPhieuNhapLayout.createSequentialGroup()
                                                .addComponent(btnHuyDonNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                                                .addComponent(btnXacNhanNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(txtMaMatHang)
                                        .addComponent(cbNhaCungCap, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtNgayNhap)
                                        .addComponent(txtSoLuongNhap)
                                        .addComponent(txtMaPhieuNhap, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnThongTinPhieuNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnTimKiemNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnThem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnTangSL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnGiamSL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
        );
        pnThongTinPhieuNhapLayout.setVerticalGroup(
                pnThongTinPhieuNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnThongTinPhieuNhapLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(pnThongTinPhieuNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lbMaPhieuNhap)
                                        .addComponent(txtMaPhieuNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnThem))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnThongTinPhieuNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnXoa)
                                        .addComponent(txtMaMatHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lbMaMatHang))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnThongTinPhieuNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lbSoLuongNhap)
                                        .addComponent(txtSoLuongNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnThongTinPhieuNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lbNgayNhap)
                                        .addComponent(txtNgayNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnTangSL))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnThongTinPhieuNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(cbNhaCungCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lbNhaCungCap)
                                        .addComponent(btnGiamSL))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                                .addGroup(pnThongTinPhieuNhapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnTimKiemNV)
                                        .addComponent(btnLamMoi)
                                        .addComponent(btnHuyDonNhap)
                                        .addComponent(btnXacNhanNhap))
                                .addContainerGap())
        );

        spDanhSachMatHang.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách mặt hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 13))); // NOI18N

        tbDanhSachMatHang.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {},
                        {},
                        {},
                        {}
                },
                new String [] {

                }
        ));
        spDanhSachMatHang.setViewportView(tbDanhSachMatHang);

        spDanhSachMatHangNhap.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách mặt hàng nhập", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 13))); // NOI18N

        tbDanhSachMatHangNhap.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {},
                        {},
                        {},
                        {}
                },
                new String [] {

                }
        ));
        spDanhSachMatHangNhap.setViewportView(tbDanhSachMatHangNhap);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(pnThongTinPhieuNhap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(spDanhSachMatHang))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spDanhSachMatHangNhap, javax.swing.GroupLayout.DEFAULT_SIZE, 613, Short.MAX_VALUE)
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(spDanhSachMatHangNhap)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(pnThongTinPhieuNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(spDanhSachMatHang, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE)))
                                .addContainerGap())
        );
    }// </editor-fold>

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {
        refreshData();
    }

    private void btnTimKiemNVActionPerformed(java.awt.event.ActionEvent evt) {
        new DialogTimKiemGUI(new Frame(), true,"MH").setVisible(true); // mở form tìm kiếm
        MatHangDTO matHangDTO = _SaveData.matHangTimThay;
        if(matHangDTO != null) {
            ArrayList<MatHangDTO> listMatHang = new ArrayList<>();
            listMatHang.add(matHangDTO);

            loadMatHang(listMatHang); // khởi tạo lại table khách hàng

            // load các thông tin của mặt hàng lên text field


            // reset lại data tìm kiếm trong local
            _SaveData.khachHangTimThay = null;
        }
    }

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void btnTangSLActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void btnGiamSLActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void btnXacNhanNhapActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void btnHuyDonNhapActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void tbDanhSachMatHangMouseListener(MouseEvent e) {
        try {
            int selectedRow = tbDanhSachMatHang.getSelectedRow();
            String idMH = String.valueOf(tbDanhSachMatHang.getValueAt(selectedRow, 0));
            MatHangDTO matHangDTO = MatHangBUS.getItemByID(idMH);

            if(matHangDTO != null) {
                loadForm(matHangDTO); // load form mặt hàng
            }
        } catch (Exception ex) {
            _MessageDialogHelper.showErrorDialog(parentForm,
                    "Vui lòng chọn một dòng trong danh sách mặt hàng!", "Yêu cầu chọn dữ liệu");
        }
    }

    private MatHangDTO tbDanhSachMatHangNhapMouseListener(MouseEvent e) {
        try {
            int selectedRow = tbDanhSachMatHangNhap.getSelectedRow();
            String idMH = String.valueOf(tbDanhSachMatHangNhap.getValueAt(selectedRow, 0));
            return MatHangBUS.getItemByID(idMH);

        } catch (Exception ex) {
            _MessageDialogHelper.showErrorDialog(parentForm,
                    "Vui lòng chọn một dòng trong danh sách mặt hàng!", "Yêu cầu chọn dữ liệu");
            return null;
        }
    }


    private void refreshData() {
        txtMaMatHang.setText(""); // refresh form mã mặt hàng
        txtMaPhieuNhap.setText(""); // refresh form tên mã phiêu nhập
        txtSoLuongNhap.setText(""); // refresh form số lượng nhập
        txtNgayNhap.setText(""); // refresh ngày nhập
        cbNhaCungCap.setSelectedIndex(0);
        tbDanhSachMatHang.clearSelection();

        // set Background
        txtMaMatHang.setBackground(Color.WHITE);
        txtMaPhieuNhap.setBackground(Color.WHITE);
        txtSoLuongNhap.setBackground(Color.WHITE);
        txtNgayNhap.setBackground(Color.WHITE);

        // set Foreground
        txtMaMatHang.setForeground(Color.BLACK);
        txtMaPhieuNhap.setForeground(Color.BLACK);
        txtSoLuongNhap.setForeground(Color.BLACK);
        txtNgayNhap.setForeground(Color.BLACK);

        loadMatHang(new MatHangBUS().getData()); // load lại mặt hàng
        loadMatHang(new ArrayList<>()); // load lại chi tiết phiếu nhập
    }

    private void loadMatHang(ArrayList<MatHangDTO> listMatHang) {
        modelTable_MH.setRowCount(0);
        for (MatHangDTO item : listMatHang) {
            modelTable_MH.addRow(new Object[]{
                    item.getMaMH(),
                    item.getMaLMH(),
                    item.getTenMH(),
                    item.getThanhTien(),
                    item.getSoLuong(),
                    item.getStatus() == 1 ? "Còn bán" : "Ngừng bán"
            });
        }
    }

    private void loadCTPN(ArrayList<MatHangDTO> listMatHang) {
        modelTable_CTPN.setRowCount(0);
        for (MatHangDTO item : listMatHang) {
            modelTable_CTPN.addRow(new Object[]{
                    item.getMaMH(),
                    item.getMaLMH(),
                    item.soLuong_hientai,
            });
        }
    }

    public void loadForm(MatHangDTO matHangDTO) {
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd hh:mm:ss");
        txtNgayNhap.setText(dateFormat.format(new Date()));
        txtMaPhieuNhap.setText(handleMHD());
        txtMaMatHang.setText(matHangDTO.getMaMH());
        txtSoLuongNhap.setText("1");
    }


    public String handleMHD() {
        String maPN = "PN";
        String[] arr = txtNgayNhap.getText().split(" ");
        for (int i = 0; i < arr.length; i++) {
            if (i == 0) {
                String[] supArr = arr[i].split("-");
                for (String item : supArr) {
                    maPN = maPN.concat(item);
                }
            } else {
                String[] supArr = arr[i].split(":");
                for (String item : supArr) {
                    maPN = maPN.concat(item);
                }
            }
        }
        return maPN;
    }

    // Variables declaration - do not modify
    private javax.swing.JButton btnGiamSL;
    private javax.swing.JButton btnHuyDonNhap;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnTangSL;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiemNV;
    private javax.swing.JButton btnXacNhanNhap;
    private javax.swing.JComboBox<String> cbNhaCungCap;
    private javax.swing.JLabel lbMaMatHang;
    private javax.swing.JLabel lbMaPhieuNhap;
    private javax.swing.JLabel lbNgayNhap;
    private javax.swing.JLabel lbNhaCungCap;
    private javax.swing.JLabel lbSoLuongNhap;
    private javax.swing.JPanel pnThongTinPhieuNhap;
    private javax.swing.JScrollPane spDanhSachMatHang;
    private javax.swing.JScrollPane spDanhSachMatHangNhap;
    private javax.swing.JTable tbDanhSachMatHang;
    private javax.swing.JTable tbDanhSachMatHangNhap;
    private javax.swing.JTextField txtMaMatHang;
    private javax.swing.JTextField txtMaPhieuNhap;
    private javax.swing.JTextField txtNgayNhap;
    private javax.swing.JTextField txtSoLuongNhap;
    // End of variables declaration
    // End of variables declaration
}

