/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package main.mini_store_manager_form;

/**
 *
 * @author edgar
 */
public class BanHangGUI extends javax.swing.JPanel {

    /**
     * Creates new form BanHangGUI
     */
    public BanHangGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 692, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_LapHoaDon;
    private javax.swing.JButton btn_LapHoaDon1;
    private javax.swing.JButton btn_LapHoaDon2;
    private javax.swing.JLabel lb_NVLapHD;
    private javax.swing.JLabel lb_NVLapHD1;
    private javax.swing.JLabel lb_NVLapHD2;
    private javax.swing.JLabel lb_NVLapHD_Res;
    private javax.swing.JLabel lb_NVLapHD_Res1;
    private javax.swing.JLabel lb_NVLapHD_Res2;
    private javax.swing.JLabel lb_NgayLap;
    private javax.swing.JLabel lb_NgayLap1;
    private javax.swing.JLabel lb_NgayLap2;
    private javax.swing.JLabel lb_SoLuong;
    private javax.swing.JLabel lb_SoLuong1;
    private javax.swing.JLabel lb_SoLuong2;
    private javax.swing.JLabel lb_TongHoaDon;
    private javax.swing.JLabel lb_TongHoaDon1;
    private javax.swing.JLabel lb_TongHoaDon2;
    private javax.swing.JPanel pn_Result;
    private javax.swing.JPanel pn_Result1;
    private javax.swing.JPanel pn_Result2;
    private javax.swing.JTextField txtTongHoaDon;
    private javax.swing.JTextField txtTongHoaDon1;
    private javax.swing.JTextField txtTongHoaDon2;
    private javax.swing.JTextField txt_NgayLap;
    private javax.swing.JTextField txt_NgayLap1;
    private javax.swing.JTextField txt_NgayLap2;
    private javax.swing.JTextField txt_SoLuong;
    private javax.swing.JTextField txt_SoLuong1;
    private javax.swing.JTextField txt_SoLuong2;
    // End of variables declaration//GEN-END:variables
}
